monitor.alsa.rules = [
  {
    matches = [{ node.name = "~alsa_output.usb-.*" }]
    actions = {
      update-props = { priority.session = 100 }
    }
  }
  {
    matches = [{ node.name = "~alsa_output.pci-.*analog-stereo" }]
    actions = {
      update-props = { priority.session = 1000 }
    }
  }
  {
    matches = [
      { node.name = "~alsa_output.pci-.*hdmi.*" }
      { node.name = "~alsa_output.pci-.*dp.*" }
    ]
    actions = {
      update-props = { priority.session = 500 }
    }
  }
  {
    matches = [{ node.name = "~alsa_input.usb-.*" }]
    actions = {
      update-props = { priority.session = 3500 }
    }
  }
  {
    matches = [{ node.name = "~alsa_input.pci-.*analog-stereo" }]
    actions = {
      update-props = { priority.session = 1000 }
    }
  }
]

monitor.bluez.rules = [
  {
    matches = [{ node.name = "~bluez_output.*" }]
    actions = {
      update-props = { priority.session = 3000 }
    }
  }
  {
    matches = [{ node.name = "~bluez_input.*" }]
    actions = {
      update-props = {
        priority.session = 800
        node.target = false
      }
    }
  }
  {
    matches = [{ node.name = "~bluez_capture_internal.*" }]
    actions = {
      update-props = {
        node.passive = true
        node.target = false
      }
    }
  }
]
