# ═══════════════════════════════════════════════════════════════════════════
# OXOCARBON — IBM Carbon Design System
# ═══════════════════════════════════════════════════════════════════════════

background              #161616
foreground              #f2f4f8
selection_background    #2d3130
selection_foreground    #f2f4f8
cursor                  #78a9ff
cursor_text_color       #161616

url_color               #3ddbd9

active_tab_background   #78a9ff
active_tab_foreground   #161616
inactive_tab_background #262626
inactive_tab_foreground #8d9095

mark1_background        #78a9ff
mark1_foreground        #161616
mark2_background        #42be65
mark2_foreground        #161616
mark3_background        #be95ff
mark3_foreground        #161616

color0                  #262626
color1                  #ee5396
color2                  #42be65
color3                  #ffe97b
color4                  #78a9ff
color5                  #be95ff
color6                  #3ddbd9
color7                  #dde1e6
color8                  #393939
color9                  #ff7eb6
color10                 #42be65
color11                 #ffe97b
color12                 #78a9ff
color13                 #be95ff
color14                 #3ddbd9
color15                 #ffffff
