-- ═══════════════════════════════════════════════════════════════════════════════
-- {{ meta.name }} Theme for Neovim
-- Generated by theme-manager.py
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}

M.colors = {
	-- Base
	bg0 = "#{{ base_bg0 }}",
	bg1 = "#{{ base_bg1 }}",
	bg2 = "#{{ base_bg2 }}",
	bg3 = "#{{ base_bg3 }}",
	bg4 = "#{{ base_bg4 }}",

	fg = "#{{ base_fg1 }}",
	fg_dim = "#{{ base_fg3 }}",
	fg_bright = "#{{ base_fg0 }}",
	fg_muted = "#{{ ui_comment }}",

	-- Accents
	red = "#{{ accent_red }}",
	orange = "#{{ accent_orange }}",
	pink = "#{{ accent_purple }}",
	yellow = "#{{ accent_yellow }}",
	gold = "#{{ accent_yellow }}",
	green = "#{{ accent_green }}",
	aqua = "#{{ accent_aqua }}",
	blue = "#{{ accent_blue }}",
	sky = "#{{ accent_blue }}",
	purple = "#{{ accent_purple }}",
	magenta = "#{{ accent_purple }}",

	-- UI
	cursor = "#{{ ui_cursor_bg }}",
	cursor_bg = "#{{ ui_cursor_fg }}",
	line = "#{{ base_bg1 }}",
	visual = "#{{ ui_visual }}",
	selection = "#{{ ui_selection }}",
	border = "#{{ ui_border }}",
	border_dim = "#{{ base_bg3 }}",
	comment = "#{{ ui_comment }}",

	-- Git
	git_add = "#{{ accent_green }}",
	git_change = "#{{ accent_yellow }}",
	git_delete = "#{{ accent_red }}",
	git_conflict = "#{{ accent_orange }}",

	-- Diagnostics
	diagnostic_error = "#{{ accent_red }}",
	diagnostic_warn = "#{{ accent_yellow }}",
	diagnostic_info = "#{{ accent_blue }}",
	diagnostic_hint = "#{{ accent_aqua }}",

	-- Syntax
	constant = "#{{ accent_orange }}",
	string = "#{{ accent_green }}",
	func = "#{{ accent_blue }}",
	keyword = "#{{ accent_purple }}",
	variable = "#{{ base_fg1 }}",
	type = "#{{ accent_yellow }}",
	operator = "#{{ accent_aqua }}",
	number = "#{{ accent_orange }}",

	none = "NONE",
}

function M.setup()
	local c = M.colors

	local highlights = {
		-- Normal
		Normal = { fg = c.fg, bg = c.none },
		NormalFloat = { fg = c.fg, bg = c.bg0 },
		NormalNC = { fg = c.fg, bg = c.bg0 },

		-- Cursor
		Cursor = { fg = c.cursor_bg, bg = c.cursor },
		CursorLine = { bg = c.line },
		CursorColumn = { bg = c.line },
		ColorColumn = { bg = c.bg2 },

		-- Line numbers
		LineNr = { fg = c.bg4 },
		CursorLineNr = { fg = c.yellow, bold = true },
		SignColumn = { fg = c.bg4, bg = c.none },

		-- Selection
		Visual = { bg = c.visual },
		VisualNOS = { bg = c.visual },

		-- Search
		Search = { fg = c.bg0, bg = c.yellow },
		IncSearch = { fg = c.bg0, bg = c.orange },
		CurSearch = { fg = c.bg0, bg = c.red },

		-- Popup menu
		Pmenu = { fg = c.fg, bg = c.bg1 },
		PmenuSel = { fg = c.fg_bright, bg = c.bg3, bold = true },
		PmenuSbar = { bg = c.bg2 },
		PmenuThumb = { bg = c.green },

		-- Status line
		StatusLine = { fg = c.fg, bg = c.bg1 },
		StatusLineNC = { fg = c.bg4, bg = c.bg0 },

		-- Tabs
		TabLine = { fg = c.bg4, bg = c.bg2 },
		TabLineSel = { fg = c.fg_bright, bg = c.bg3, bold = true },
		TabLineFill = { bg = c.bg0 },

		-- Splits
		VertSplit = { fg = c.border_dim },
		WinSeparator = { fg = c.border_dim },
		FloatBorder = { fg = c.border, bg = c.bg0 },

		-- Folds
		Folded = { fg = c.bg4, bg = c.bg1 },
		FoldColumn = { fg = c.bg4, bg = c.bg0 },

		-- Diff
		DiffAdd = { fg = c.git_add, bg = c.bg2 },
		DiffChange = { fg = c.git_change, bg = c.bg2 },
		DiffDelete = { fg = c.git_delete, bg = c.bg2 },
		DiffText = { fg = c.fg_bright, bg = c.bg3, bold = true },

		-- Spell
		SpellBad = { sp = c.diagnostic_error, undercurl = true },
		SpellCap = { sp = c.diagnostic_warn, undercurl = true },
		SpellLocal = { sp = c.diagnostic_info, undercurl = true },
		SpellRare = { sp = c.purple, undercurl = true },

		-- Messages
		ErrorMsg = { fg = c.error, bold = true },
		WarningMsg = { fg = c.warning, bold = true },
		ModeMsg = { fg = c.blue, bold = true },
		MoreMsg = { fg = c.success, bold = true },
		Question = { fg = c.blue },

		-- Other
		NonText = { fg = c.bg4 },
		SpecialKey = { fg = c.bg4 },
		EndOfBuffer = { fg = c.bg0 },

		-- Comments
		Comment = { fg = c.comment, italic = true },

		-- Constants
		Constant = { fg = c.constant },
		String = { fg = c.string },
		Character = { fg = c.string },
		Number = { fg = c.number },
		Boolean = { fg = c.constant },
		Float = { fg = c.number },

		-- Identifiers
		Identifier = { fg = c.variable },
		Function = { fg = c.func, bold = true },

		-- Statements
		Statement = { fg = c.keyword, bold = true },
		Conditional = { fg = c.keyword },
		Repeat = { fg = c.keyword },
		Label = { fg = c.keyword },
		Operator = { fg = c.operator },
		Keyword = { fg = c.keyword },
		Exception = { fg = c.red, bold = true },

		-- Preproc
		PreProc = { fg = c.purple },
		Include = { fg = c.purple },
		Define = { fg = c.purple },
		Macro = { fg = c.purple },
		PreCondit = { fg = c.purple },

		-- Types
		Type = { fg = c.type },
		StorageClass = { fg = c.keyword },
		Structure = { fg = c.type },
		Typedef = { fg = c.type },

		-- Special
		Special = { fg = c.orange },
		SpecialChar = { fg = c.pink },
		Tag = { fg = c.orange },
		Delimiter = { fg = c.fg_dim },
		SpecialComment = { fg = c.pink, italic = true },
		Debug = { fg = c.red },
		Underlined = { underline = true },
		Ignore = { fg = c.bg4 },
		Error = { fg = c.error, bold = true },
		Todo = { fg = c.yellow, bg = c.bg3, bold = true },

		-- Diagnostics
		DiagnosticError = { fg = c.diagnostic_error },
		DiagnosticWarn = { fg = c.diagnostic_warn },
		DiagnosticInfo = { fg = c.diagnostic_info },
		DiagnosticHint = { fg = c.diagnostic_hint },
		DiagnosticUnderlineError = { sp = c.diagnostic_error, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.diagnostic_warn, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.diagnostic_info, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.diagnostic_hint, undercurl = true },

		-- Git Signs
		GitSignsAdd = { fg = c.git_add },
		GitSignsChange = { fg = c.git_change },
		GitSignsDelete = { fg = c.git_delete },
	}

	for group, settings in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, settings)
	end
end

return M
