################
### MONITORS ###
################

monitor = DP-2, 3440x1440@165, 0x0, 1
monitor = eDP-1, disabled

# Workspaces 1-5 on main monitor
workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2

# Workspaces 6-10 on laptop screen
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1
