################
### MONITORS ###
################

# laptop right
# monitor = DP-2, 3440x1440@165, 0x0, 1
# monitor = eDP-1, 1920x1080@60.00, 3440x0, 1

# laptop left
# monitor = eDP-1, 1920x1080@60.00, 0x0, 1
# monitor = DP-2, 3440x1440@165, 1920x0, 1

# laptop bottom
monitor = DP-2, 3440x1440@165, 0x0, 1
monitor = eDP-1, 1920x1080@60.00, 760x1440, 1

# Workspaces 1-5 on main monitor
workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2

# Workspaces 6-10 on laptop screen
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1
