###################
### MY PROGRAMS ###
###################

# $terminal = ghostty --config-file=$HOME/.config/ghostty/config
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$browser = firefox

