-- ═══════════════════════════════════════════════════════════════════════════
-- OXOCARBON — IBM Carbon Design System
-- ═══════════════════════════════════════════════════════════════════════════

local M = {}

M.colors = {
	bg0 = "#0d0d0d",
	bg1 = "#161616",
	bg2 = "#1c1c1c",
	bg3 = "#262626",
	bg4 = "#393939",

	fg = "#f2f4f8",
	fg_dim = "#dde1e6",
	fg_bright = "#ffffff",
	fg_muted = "#8d9095",

	red = "#ee5396",
	red_bright = "#ff7eb6",
	red_dim = "#ee5396",

	orange = "#ff832b",
	orange_bright = "#ff832b",
	orange_dim = "#ff832b",

	pink = "#ff7eb6",
	pink_bright = "#ff7eb6",
	pink_dim = "#ff7eb6",

	yellow = "#ffe97b",
	gold = "#ffe97b",

	green = "#42be65",
	aqua = "#3ddbd9",
	blue = "#78a9ff",
	sky = "#33b1ff",

	purple = "#be95ff",
	magenta = "#ff7eb6",

	gray0 = "#393939",
	gray1 = "#525252",
	gray2 = "#6f6f6f",
	gray3 = "#8d9095",

	success = "#42be65",
	warning = "#ffe97b",
	error = "#ee5396",
	info = "#78a9ff",

	cursor = "#78a9ff",
	cursor_bg = "#161616",
	line = "#1c1c1c",
	visual = "#2d3130",
	selection = "#393939",

	border = "#78a9ff",
	border_dim = "#393939",

	comment = "#6f6f6f",
	constant = "#ff832b",
	string = "#42be65",
	func = "#78a9ff",
	keyword = "#be95ff",
	variable = "#f2f4f8",
	type = "#ffe97b",
	operator = "#3ddbd9",
	number = "#ff832b",

	git_add = "#42be65",
	git_change = "#ffe97b",
	git_delete = "#ee5396",
	git_conflict = "#ff832b",

	diagnostic_error = "#ee5396",
	diagnostic_warn = "#ffe97b",
	diagnostic_info = "#78a9ff",
	diagnostic_hint = "#3ddbd9",

	none = "NONE",
}

function M.setup()
	local c = M.colors

	local highlights = {
		Normal = { fg = c.fg, bg = c.none },
		NormalFloat = { fg = c.fg, bg = c.none },
		NormalNC = { fg = c.fg, bg = c.none },

		Cursor = { fg = c.cursor_bg, bg = c.cursor },
		CursorLine = { bg = c.line },
		CursorColumn = { bg = c.line },
		ColorColumn = { bg = c.bg2 },

		LineNr = { fg = c.gray1 },
		CursorLineNr = { fg = c.yellow, bold = true },
		SignColumn = { fg = c.gray1, bg = c.none },

		Visual = { bg = c.visual },
		VisualNOS = { bg = c.visual },

		Search = { fg = c.bg0, bg = c.yellow },
		IncSearch = { fg = c.bg0, bg = c.orange },
		CurSearch = { fg = c.bg0, bg = c.red },

		Pmenu = { fg = c.fg, bg = c.bg2 },
		PmenuSel = { fg = c.fg_bright, bg = c.bg3, bold = true },
		PmenuSbar = { bg = c.bg3 },
		PmenuThumb = { bg = c.blue },

		StatusLine = { fg = c.fg, bg = c.none },
		StatusLineNC = { fg = c.gray1, bg = c.none },

		TabLine = { fg = c.gray2, bg = c.bg2 },
		TabLineSel = { fg = c.fg_bright, bg = c.bg3, bold = true },
		TabLineFill = { bg = c.bg1 },

		VertSplit = { fg = c.border_dim },
		WinSeparator = { fg = c.border_dim },
		FloatBorder = { fg = c.border, bg = c.bg2 },

		Folded = { fg = c.gray2, bg = c.bg2 },
		FoldColumn = { fg = c.gray1, bg = c.bg1 },

		DiffAdd = { fg = c.git_add, bg = c.bg2 },
		DiffChange = { fg = c.git_change, bg = c.bg2 },
		DiffDelete = { fg = c.git_delete, bg = c.bg2 },
		DiffText = { fg = c.fg_bright, bg = c.bg3, bold = true },

		SpellBad = { sp = c.error, undercurl = true },
		SpellCap = { sp = c.warning, undercurl = true },
		SpellLocal = { sp = c.info, undercurl = true },
		SpellRare = { sp = c.purple, undercurl = true },

		ErrorMsg = { fg = c.error, bold = true },
		WarningMsg = { fg = c.warning, bold = true },
		ModeMsg = { fg = c.blue, bold = true },
		MoreMsg = { fg = c.success, bold = true },
		Question = { fg = c.blue },

		NonText = { fg = c.fg },
		SnacksPickerGitStatusUntracked = { fg = c.fg, bg = c.none },

		Comment = { fg = c.comment, italic = true },
		Constant = { fg = c.constant },
		String = { fg = c.string },
		Character = { fg = c.string },
		Number = { fg = c.number },
		Boolean = { fg = c.constant },
		Float = { fg = c.number },
		Identifier = { fg = c.variable },
		Function = { fg = c.func, bold = true },
		Statement = { fg = c.keyword, bold = true },
		Conditional = { fg = c.keyword },
		Repeat = { fg = c.keyword },
		Label = { fg = c.keyword },
		Operator = { fg = c.operator },
		Keyword = { fg = c.keyword },
		Exception = { fg = c.red_bright },
		PreProc = { fg = c.purple },
		Include = { fg = c.purple },
		Define = { fg = c.purple },
		Macro = { fg = c.purple },
		PreCondit = { fg = c.purple },
		Type = { fg = c.type },
		StorageClass = { fg = c.keyword },
		Structure = { fg = c.type },
		Typedef = { fg = c.type },
		Special = { fg = c.orange_bright },
		SpecialChar = { fg = c.pink },
		Tag = { fg = c.orange },
		Delimiter = { fg = c.fg_dim },
		SpecialComment = { fg = c.pink, italic = true },
		Debug = { fg = c.red_bright },
		Underlined = { underline = true },
		Ignore = { fg = c.gray1 },
		Error = { fg = c.error, bold = true },
		Todo = { fg = c.yellow, bg = c.bg3, bold = true },

		DiagnosticError = { fg = c.diagnostic_error },
		DiagnosticWarn = { fg = c.diagnostic_warn },
		DiagnosticInfo = { fg = c.diagnostic_info },
		DiagnosticHint = { fg = c.diagnostic_hint },
		DiagnosticUnderlineError = { sp = c.diagnostic_error, undercurl = true },
		DiagnosticUnderlineWarn = { sp = c.diagnostic_warn, undercurl = true },
		DiagnosticUnderlineInfo = { sp = c.diagnostic_info, undercurl = true },
		DiagnosticUnderlineHint = { sp = c.diagnostic_hint, undercurl = true },

		["@lsp.type.class"] = { fg = c.type },
		["@lsp.type.decorator"] = { fg = c.purple },
		["@lsp.type.enum"] = { fg = c.type },
		["@lsp.type.enumMember"] = { fg = c.constant },
		["@lsp.type.function"] = { fg = c.func, bold = true },
		["@lsp.type.interface"] = { fg = c.type },
		["@lsp.type.macro"] = { fg = c.purple },
		["@lsp.type.method"] = { fg = c.func },
		["@lsp.type.namespace"] = { fg = c.type },
		["@lsp.type.parameter"] = { fg = c.variable },
		["@lsp.type.property"] = { fg = c.variable },
		["@lsp.type.struct"] = { fg = c.type },
		["@lsp.type.type"] = { fg = c.type },
		["@lsp.type.typeParameter"] = { fg = c.type },
		["@lsp.type.variable"] = { fg = c.variable },

		["@variable"] = { fg = c.variable },
		["@variable.builtin"] = { fg = c.red },
		["@variable.parameter"] = { fg = c.variable },
		["@variable.member"] = { fg = c.variable },
		["@constant"] = { fg = c.constant },
		["@constant.builtin"] = { fg = c.constant },
		["@constant.macro"] = { fg = c.purple },
		["@string"] = { fg = c.string },
		["@string.escape"] = { fg = c.pink },
		["@string.regexp"] = { fg = c.pink },
		["@character"] = { fg = c.string },
		["@number"] = { fg = c.number },
		["@boolean"] = { fg = c.constant },
		["@float"] = { fg = c.number },
		["@function"] = { fg = c.func, bold = true },
		["@function.builtin"] = { fg = c.func },
		["@function.macro"] = { fg = c.purple },
		["@function.call"] = { fg = c.func },
		["@method"] = { fg = c.func },
		["@method.call"] = { fg = c.func },
		["@constructor"] = { fg = c.type },
		["@keyword"] = { fg = c.keyword, bold = true },
		["@keyword.function"] = { fg = c.keyword },
		["@keyword.operator"] = { fg = c.operator },
		["@keyword.return"] = { fg = c.keyword },
		["@keyword.conditional"] = { fg = c.keyword },
		["@keyword.repeat"] = { fg = c.keyword },
		["@keyword.exception"] = { fg = c.red_bright },
		["@operator"] = { fg = c.operator },
		["@type"] = { fg = c.type },
		["@type.builtin"] = { fg = c.type },
		["@type.definition"] = { fg = c.type },
		["@punctuation.delimiter"] = { fg = c.fg_dim },
		["@punctuation.bracket"] = { fg = c.fg_dim },
		["@punctuation.special"] = { fg = c.orange_bright },
		["@comment"] = { fg = c.comment, italic = true },
		["@comment.todo"] = { fg = c.yellow, bg = c.bg3, bold = true },
		["@comment.warning"] = { fg = c.warning, bold = true },
		["@comment.note"] = { fg = c.info, bold = true },
		["@comment.error"] = { fg = c.error, bold = true },
		["@tag"] = { fg = c.orange },
		["@tag.attribute"] = { fg = c.purple },
		["@tag.delimiter"] = { fg = c.fg_dim },

		GitSignsAdd = { fg = c.git_add },
		GitSignsChange = { fg = c.git_change },
		GitSignsDelete = { fg = c.git_delete },

		TelescopeBorder = { fg = c.border },
		TelescopePromptBorder = { fg = c.blue },
		TelescopeResultsBorder = { fg = c.border_dim },
		TelescopePreviewBorder = { fg = c.border_dim },
		TelescopeSelection = { fg = c.fg_bright, bg = c.bg3, bold = true },
		TelescopeMatching = { fg = c.blue, bold = true },

		NeoTreeNormal = { fg = c.fg, bg = c.bg0 },
		NeoTreeNormalNC = { fg = c.fg, bg = c.bg0 },
		NeoTreeRootName = { fg = c.blue, bold = true },
		NeoTreeFileName = { fg = c.fg },
		NeoTreeFileNameOpened = { fg = c.blue },
		NeoTreeGitAdded = { fg = c.git_add },
		NeoTreeGitModified = { fg = c.git_change },
		NeoTreeGitDeleted = { fg = c.git_delete },
		NeoTreeGitConflict = { fg = c.git_conflict },
		NeoTreeIndentMarker = { fg = c.gray1 },

		WhichKey = { fg = c.blue },
		WhichKeyGroup = { fg = c.purple },
		WhichKeyDesc = { fg = c.fg },
		WhichKeySeparator = { fg = c.gray1 },
		WhichKeyFloat = { bg = c.bg2 },

		CmpItemAbbrMatch = { fg = c.blue, bold = true },
		CmpItemAbbrMatchFuzzy = { fg = c.blue },
		CmpItemKindFunction = { fg = c.func },
		CmpItemKindMethod = { fg = c.func },
		CmpItemKindVariable = { fg = c.variable },
		CmpItemKindKeyword = { fg = c.keyword },
		CmpItemKindText = { fg = c.fg },
		CmpItemKindClass = { fg = c.type },
		CmpItemKindInterface = { fg = c.type },

		IndentBlanklineChar = { fg = c.bg3 },
		IndentBlanklineContextChar = { fg = c.blue },

		DashboardHeader = { fg = c.blue },
		DashboardCenter = { fg = c.aqua },
		DashboardShortCut = { fg = c.purple },
		DashboardFooter = { fg = c.pink, italic = true },

		NotifyBackground = { bg = c.bg1 },
		NotifyERRORBorder = { fg = c.error },
		NotifyWARNBorder = { fg = c.warning },
		NotifyINFOBorder = { fg = c.info },
		NotifyDEBUGBorder = { fg = c.purple },
		NotifyTRACEBorder = { fg = c.pink },

		FlashLabel = { fg = c.bg0, bg = c.blue, bold = true },
		FlashMatch = { fg = c.blue },
		FlashCurrent = { fg = c.red, bold = true },

		SnacksNotifierBorderInfo = { fg = c.info },
		SnacksNotifierBorderWarn = { fg = c.warning },
		SnacksNotifierBorderError = { fg = c.error },
		SnacksNotifierBorderDebug = { fg = c.purple },
		SnacksNotifierBorderTrace = { fg = c.pink },
	}

	for group, settings in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, settings)
	end
end

return M
